# Generated by Django 5.2.9 on 2025-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_options_task_admin_notes_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('user_completed', 'Marked Completed by User'), ('approved', 'Approved by Admin')], default='pending', max_length=32),
        ),
    ]
